image: rambabusaravanan/firebase

stages:
  - deploy

deploy-dev:
  stage: deploy
  only:
    - develop
  script:
    - yarn
    - yarn run build
    - firebase use arctec-dashboard-dev-2 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
